# wait for playbook
- hosts: tek
  become: true
  tasks:
   - name: package installation
     yum: pkg=httpd state=present
   - name: wait for service listening on httpd
     wait_for:
        state: started
    
