# wait for playbook
- hosts: tek
  become: true
  tasks:
   - name: package installation
     yum: pkg=vsftpd state=present
   - name: wait for service listening on port 21
     wait_for:
       port: 21
       state: started

   - name: create new file on koti
     wait_for:
       path: /home/tekteacher/koti
    
